---
- name: install git
  yum:
    name: git
    state: installed 

-  name: git clone
   git:
    repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
    dest: /var/www/html/
    clone: yes
